### ISSUE TITLE
Some problem during patch extraction

### ISSUE THREAD

**Issue by DavidGuo4Real** [clemsgrs/hs2p#12]
Hi there. Thank you for this useful tool. When I was using it for patch extraction, the following problem occurred:

```
Exception in thread Thread-3 (_handle_results):
Traceback (most recent call last):
  File "/mnt/home/gzr/anaconda3/envs/hs2p/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/mnt/home/gzr/anaconda3/envs/hs2p/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/home/gzr/anaconda3/envs/hs2p/lib/python3.10/multiprocessing/pool.py", line 576, in _handle_results
    task = get()
  File "/mnt/home/gzr/anaconda3/envs/hs2p/lib/python3.10/multiprocessing/connection.py", line 256, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: RegistrantNotRegisteredError.__init__() missing 2 required positional arguments: 'registrant_name' and 'register'
```

Then I set cfg.speed.multiprocessing to False, the following error occurred:

```
Error executing job with overrides: []
Traceback (most recent call last):.E5D16DBF-CABD-4C96-A794-5F27BC305055                             
  File "/home/gzr/hs2p/patch_extraction.py", line 169, in main
    seg_times, patch_times = seg_and_patch(
  File "/home/gzr/hs2p/utils.py", line 238, in seg_and_patch
    wsi_object = WholeSlideImage(slide_path, spacing, backend)
  File "/home/gzr/hs2p/source/wsi.py", line 37, in __init__
    self.wsi = wsd.WholeSlideImage(path, backend=backend)
  File "/home/gzr/anaconda3/envs/hs2p/lib/python3.10/site-packages/wholeslidedata/image/wholeslideimage.py", line 29, in __init__
    self._backend = WholeSlideImageBackend.create(backend, path=self._path)
  File "/home/gzr/anaconda3/envs/hs2p/lib/python3.10/site-packages/creationism/registration/factory.py", line 90, in create
    raise RegistrantNotRegisteredError(
creationism.registration.factory.RegistrantNotRegisteredError: 
        Registrant 'asap' is not found in the register of class 'WholeSlideImageBackend' with registrant names ('openslide',) and register classes (<class 'wholeslidedata.accessories.openslide.backend.OpenSlideWholeSlideImageBackend'>,).
```

I'm not sure what's going on here.

**Comment by clemsgrs** [comment]
hey, no problem :)
could you try to set `backend: 'pyvips'` in your config file?

if it still doesn’t work after changing the backend parameter, try with python 3.9 (i see you’re using python 3.10)

**Comment by Qing1Zhong** [comment]
I also encountered this problem, and I resolved the error by setting '`backend`' to '`openslide`'. However, I encountered a new error, and the error message is as follows: 

**Error executing job with overrides: []
Traceback (most recent call last):
  File "patch_extraction.py", line 184, in main
    backend=cfg.backend,
  File "/home/xx/CLAM/hs2p-master/utils.py", line 288, in seg_and_patch
    line_thickness=vis_params.line_thickness,
  File "/home/xx/CLAM/hs2p-master/source/wsi.py", line 310, in visWSI
    offset=offset,
cv2.error: OpenCV(4.8.0): -1: error: (-5:Bad argument) in function 'drawContours'
\> Overload resolution failed:
\>  - Layout of the output array image is incompatible with cv::Mat
\>  - Expected Ptr<cv::UMat> for argument 'image'**

In the file `wsi.py`, I added the following code to check if the input to the `cv2.drawContours()` function is correct:
```
print('\n')
print(type(img))
print(img.shape)
print(type(self.scaleContourDim(self.contours_tissue, scale)))
print(len(self.scaleContourDim(self.contours_tissue, scale)))
```
The returned results are:
```
<class 'numpy.ndarray'>
(1648, 2112, 3)
<class 'list'>
97
```
This seems to meet the input requirements of the cv2.drawContours() function. I don't understand why it is still throwing an error.🤔🤔🤔🤔🤔🤔

Additionally, I would like to know how your scaling method differs from the following method. I am trying to replicate the results of [HIPT](https://github.com/mahmoodlab/HIPT) using CLAM, but I am facing difficulties due to the 20x magnification mentioned in the paper. Most of the pathology slide images from TCGA are magnified at 40x, which is causing me some distress.

```
import openslide

magnification_40x = 1.0
magnification_20x = 2.0
patch_size_at_20x = [4096, 4096]

patch_size_at_40x = [int(x * magnification_20x) for x in patch_size_at_20x]

slide_path = "/data/xx/TCGA_BLCA/TCGA-2F-A9KR-01Z-00-DX1.D6A4BD2D-18F3-4FA6-8272-60392DDAF7B5.svs"
slide = openslide.OpenSlide(slide_path)

start_x = start_y = 0 
patch_40x = slide.read_region((start_x, start_y), 0, tuple(patch_size_at_40x))
patch_20x = patch_40x.resize(patch_size_at_20x)
```

Looking forward to your reply!🥺🥺🥺🥺🥺🥺


**Appendix**
The system and environment and system I am running the code on are as follows:
`Ubuntu 20.04`

_# Name |                   Version |                  Build  Channel_
```
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
asap                      2.0.0a8                  pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
blas                      1.0                         mkl  
braceexpand               0.1.7                    pypi_0    pypi
brotlipy                  0.7.0           py37h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.01.10           h06a4308_0  
certifi                   2022.12.7        py37h06a4308_0  
cffi                      1.15.1           py37h74dc2b5_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.6                    pypi_0    pypi
concurrentbuffer          0.0.7                    pypi_0    pypi
creationism               0.0.5                    pypi_0    pypi
cryptography              39.0.1           py37h9ce1e76_0  
cuda                      11.6.1                        0    nvidia
cuda-cccl                 11.6.55              hf6102b2_0    nvidia
cuda-command-line-tools   11.6.2                        0    nvidia
cuda-compiler             11.6.2                        0    nvidia
cuda-cudart               11.6.55              he381448_0    nvidia
cuda-cudart-dev           11.6.55              h42ad0f4_0    nvidia
cuda-cuobjdump            11.6.124             h2eeebcb_0    nvidia
cuda-cupti                11.6.124             h86345e5_0    nvidia
cuda-cuxxfilt             11.6.124             hecbf4f6_0    nvidia
cuda-driver-dev           11.6.55                       0    nvidia
cuda-gdb                  12.1.105                      0    nvidia
cuda-libraries            11.6.1                        0    nvidia
cuda-libraries-dev        11.6.1                        0    nvidia
cuda-memcheck             11.8.86                       0    nvidia
cuda-nsight               12.1.105                      0    nvidia
cuda-nsight-compute       12.1.1                        0    nvidia
cuda-nvcc                 11.6.124             hbba6d2d_0    nvidia
cuda-nvdisasm             12.1.105                      0    nvidia
cuda-nvml-dev             11.6.55              haa9ef22_0    nvidia
cuda-nvprof               12.1.105                      0    nvidia
cuda-nvprune              11.6.124             he22ec0a_0    nvidia
cuda-nvrtc                11.6.124             h020bade_0    nvidia
cuda-nvrtc-dev            11.6.124             h249d397_0    nvidia
cuda-nvtx                 11.6.124             h0630a44_0    nvidia
cuda-nvvp                 12.1.105                      0    nvidia
cuda-runtime              11.6.1                        0    nvidia
cuda-samples              11.6.101             h8efea70_0    nvidia
cuda-sanitizer-api        12.1.105                      0    nvidia
cuda-toolkit              11.6.1                        0    nvidia
cuda-tools                11.6.1                        0    nvidia
cuda-visual-tools         11.6.1                        0    nvidia
cycler                    0.11.0                   pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
gds-tools                 1.6.1.9                       0    nvidia
giflib                    5.2.1                h5eee18b_3  
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.32                   pypi_0    pypi
gmp                       6.2.1                h295c915_3  
gnutls                    3.6.15               he1e5248_0  
h5py                      3.8.0                    pypi_0    pypi
hydra-core                1.2.0                    pypi_0    pypi
idna                      3.4              py37h06a4308_0  
imageio                   2.31.1                   pypi_0    pypi
importlib-metadata        6.7.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
jpeg                      9e                   h5eee18b_1  
jsonschema                4.17.3                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libcublas                 11.9.2.110           h5e84587_0    nvidia
libcublas-dev             11.9.2.110           h5c901ab_0    nvidia
libcufft                  10.7.1.112           hf425ae0_0    nvidia
libcufft-dev              10.7.1.112           ha5ce4c0_0    nvidia
libcufile                 1.6.1.9                       0    nvidia
libcufile-dev             1.6.1.9                       0    nvidia
libcurand                 10.3.2.106                    0    nvidia
libcurand-dev             10.3.2.106                    0    nvidia
libcusolver               11.3.4.124           h33c3c4e_0    nvidia
libcusparse               11.7.2.124           h7538f96_0    nvidia
libcusparse-dev           11.7.2.124           hbbe9722_0    nvidia
libdeflate                1.17                 h5eee18b_0  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.4                h5eee18b_0  
libnpp                    11.6.3.124           hd2722f0_0    nvidia
libnpp-dev                11.6.3.124           h3c42840_0    nvidia
libnvjpeg                 11.6.2.124           hd473ad6_0    nvidia
libnvjpeg-dev             11.6.2.124           hb5906b9_0    nvidia
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.0                h6a678d5_2  
libunistring              0.9.10               h27cfd23_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
lz4-c                     1.9.4                h6a678d5_0  
matplotlib                3.5.3                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.1            py37hd3c417c_0  
mkl_random                1.2.2            py37h51133e4_0  
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.6.3                    pypi_0    pypi
nsight-compute            2023.1.1.4                    0    nvidia
numpy                     1.21.5           py37h6c91a56_3  
numpy-base                1.21.5           py37ha15fc14_3  
omegaconf                 2.3.0                    pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
opencv-python-headless    4.8.0.74                 pypi_0    pypi
openh264                  2.1.1                h4ff587b_0  
openslide-python          1.2.0                    pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0  
packaging                 23.1                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       22.3.1           py37h06a4308_0  
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
protobuf                  4.23.4                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 23.0.0           py37h06a4308_0  
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pysocks                   1.7.1                    py37_1  
python                    3.7.7                hcff3b4d_5  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.13.1          py3.7_cuda11.6_cudnn8.3.2_0    pytorch
pytorch-cuda              11.6                 h867d48c_1    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3                   pypi_0    pypi
pyvips                    2.2.1                    pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.28.1           py37h06a4308_0  
rtree                     1.0.0                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
seaborn                   0.12.2                   pypi_0    pypi
sentry-sdk                1.28.1                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                65.6.3           py37h06a4308_0  
shapely                   2.0.1                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1  
smmap                     5.0.0                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
tifffile                  2021.11.2                pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
torchaudio                0.13.1               py37_cu116    pytorch
torchvision               0.14.1               py37_cu116    pytorch
tqdm                      4.65.0                   pypi_0    pypi
typing_extensions         4.3.0            py37h06a4308_0  
urllib3                   1.26.14          py37h06a4308_0  
wandb                     0.15.5                   pypi_0    pypi
webdataset                0.2.48                   pypi_0    pypi
wheel                     0.38.4           py37h06a4308_0  
wholeslidedata            0.0.15                   pypi_0    pypi
xz                        5.4.2                h5eee18b_0  
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.5                hc292b87_0  
```

**Comment by clemsgrs** [comment]
yes, I will switch the default `backend` to `'openslide'` to avoid people running into the previous issue.

regarding your code error, i'm not quite sure what the root cause.
my first guess would be different opencv versions, so i checked the version i run the code with:

```bash
opencv-python==4.5.5.64
opencv-python-headless==4.5.5.64
```

i see you're using

```bash
opencv-python==4.7.0.72
opencv-python-headless==4.8.0.74 
```

could you try downgrading to the `4.5.5.64` version and let me know what is the outcome?

regarding the magnification question : if i understand correctly, you want to extract `(4096, 4096)` regions at `20x` (just like in HIPT paper), right? the issue is that reasoning with magnifications (`40x`, `20x`, etc..) is not optimal as the results produced is scanner-dependant. 

what you want to reason with is **pixel spacing**, which represents the physical distance spanned by one pixel. it usually is specified as a tuple (ps_x, ps_y) as it could happen that the distance spanned along the x and y axis is different (usually it's the same) ; for most scanners, the following mapping holds true:

| magnigication | pixel spacing |
|---------------|---------------|
| 40x           | 0.25 mpp      |
| 20x           | 0.50 mpp       |

where 'mpp' stands for 'microns per pixel'. 
because TCGA slides should follow the previous mapping, you can to extract `(4096, 4096)` regions at `20x` by simply specify in your yaml config file:

```yaml
patch_params:
  spacing: 0.5 
  patch_size: 4096
```

let me know if that answers your questions! happy to help further if needed

**Comment by Qing1Zhong** [comment]
Thank you so much for your response!！
I have already followed your instructions to install `opencv==4.5.5.64` and `opencv-python-headless==4.5.5.64`. However, the problem was not resolved, and the previous error still occurred. So, before calling the `cv2.drawContours()`([line 298, wsi.py](https://github.com/clemsgrs/hs2p/blob/master/source/wsi.py)) function, **I added a line of code**:
`print(img.flags, '\n')
`

**The output was as follows:**
```
C_CONTIGUOUS : False
F_CONTIGUOUS : False
OWNDATA : False
WRITEABLE : True
ALIGNED : True
WRITEBACKIFCOPY : False
UPDATEIFCOPY : False
```
This indicates that the variable img in memory **is not contiguous**, and the `cv2.drawContours()` function **requires a continuous numpy array**. I suspected that this was the reason for the error.


So, I added the following code before calling the` cv2.drawContours() `function:
`img = np.ascontiguousarray(img)
`

**This made the code run successfully!!**  🤗🤗🤗
![TCGA-2F-A9KO-01Z-00-DX1 195576CF-B739-4BD9-B15B-4A70AE287D3E](https://github.com/clemsgrs/hs2p/assets/110836197/21d962b8-603a-419e-9d43-23f7f33b79d1)
![TCGA-2F-A9KO-01Z-00-DX1 195576CF-B739-4BD9-B15B-4A70AE287D3E](https://github.com/clemsgrs/hs2p/assets/110836197/9adcafbb-fd84-4982-ab98-5bdc1fd2c975)


But I don't know why this problem occurred. I may need more time to carefully read through the code. Alternatively, could you help me answer it?

**Comment by clemsgrs** [comment]
hi, glad that you managed to get it to work!
results look good :) 

I'm not sure either why this error happened, I'll inquire and let you know if I ever come up with an explanation

**Comment by clemsgrs** [comment]
Seems the `opencv` error only happens with `backend = 'openslide'`.
I've added a check to enforce contiguous array in that case, thanks for your message :)
