### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by bryanwong17** [clemsgrs/hs2p#5]
Hi @clemsgrs, could you let me know how to fix this error? When I print out self.wsi.properties, there is no "tiff.XResolution"

Also, should I modify filter_params.ref_patch_size (512) in default.yaml if I want to extract [4096,4096] patches with spacing 0.5?

![image](https://user-images.githubusercontent.com/67773304/209028788-08a703e5-9e0b-405a-96f7-fe5672acbd4b.png)

**Comment by clemsgrs** [comment]
hi, I've merged some changes I had made and forgot to add here.
the overall use should be more user-friendly (see new `README.md`)

also, I've added comments to the config file describing what's the purpose of each parameter.
you can leave `filter_params.ref_patch_size` to 512, it doesn't influence patch sizes at a given spacing.

if the issue with `tiff.XResolution` persists, it might be because the spacing / resolution is missing for a few TCGA slides.
I'll try to add some code to show how one can force a given spacing at a given level.

**Comment by bryanwong17** [comment]
Hi @clemsgrs, I tried to rerun again with the new environment which was installed from requirements.txt

However, I met the below error. Do you perhaps know how to solve it?

(hs2p) PS C:\hs2p> python .\main.py --config_name default.yaml
Traceback (most recent call last):
  File "C:\hs2p\main.py", line 11, in <module>
    from utils import initialize_wandb, seg_and_patch
  File "C:\hs2p\utils.py", line 10, in <module>
    from source.wsi import WholeSlideImage
  File "C:\hs2p\source\wsi.py", line 9, in <module>
    import openslide
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\user\anaconda3\lib\site-packages\openslide_python-1.1.2-py3.9-win-amd64.egg\openslide\__init__.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\user\anaconda3\lib\site-packages\openslide_python-1.1.2-py3.9-win-amd64.egg\openslide\lowlevel.py", line 56, in <module>
  File "C:\Users\user\anaconda3\lib\ctypes\__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\user\anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

**Comment by bryanwong17** [comment]
Hi @clemsgrs, I tried to rerun again with the new environment which was installed from requirements.txt

However, I met the below error. Do you perhaps know how to solve it?

Traceback (most recent call last):
  File "C:\hs2p\main.py", line 11, in <module>
    from utils import initialize_wandb, seg_and_patch
  File "C:\hs2p\utils.py", line 10, in <module>
    from source.wsi import WholeSlideImage
  File "C:\hs2p\source\wsi.py", line 9, in <module>
    import openslide
  File "C:\Users\user\anaconda3\envs\hs2p\Lib\site-packages\openslide\__init__.py", line 30, in <module>
    from openslide import lowlevel
  File "C:\Users\user\anaconda3\envs\hs2p\Lib\site-packages\openslide\lowlevel.py", line 54, in <module>
    _lib = cdll.LoadLibrary('libopenslide-0.dll')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\envs\hs2p\Lib\ctypes\__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\anaconda3\envs\hs2p\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by bryanwong17** [comment]
Hi @clemsgrs, I tried to rerun again. and the issue was with tiff.XResolution still exists. 

Could you please let me know if you have already fixed it? FYI, I'm using Camelyon16. Does it work with TCGA slides?

**Comment by bryanwong17** [comment]
Hi @clemsgrs, thanks for the answer. Now I can extract patches, but I receive a warning like this:

WARNING: target spacing and actual spacing are more than 15% apart!

Is it a big deal?

Thanks!

**Comment by clemsgrs** [comment]
not a big deal at all
if you pull latest version of master, this warning should be removed

did it end up working for CAMELYON16?

**Comment by bryanwong17** [comment]
Thanks for the confirmation.

Only a few slides of CAMELYON16 have been tested, and they all worked perfectly!
